# === About JAC ===

# JAC meeting room.
jacroom: Perloff 1102
# JAC meeting time.
jactime: 7-9PM
# JAC meeting day.
jacday: Thursdays
# Information about JAC.
# Written in markdown.
# The line "%photos%" is replaced with the photo slideshow.
jacabout: |
 We're the Japanese Animation Club at UCLA! Welcome to our site! (ﾉ´ヮ´)ﾉ*:･ﾟ✧

 We’re a club dedicated to facilitating both on and off-campus gatherings for the appreciation of Japanese anime and culture! We welcome all anime fans to join us at our club-hosted events and local conventions, to meet with others who share the same passion for art and entertainment.

 %photos%

 We hold weekly club meetings. Please join us for screenings, awesome events, raffles, karaoke, cosplay, and much, much more!

 JAC is part of a larger network of collegiate anime clubs in California called "Cal Animage". The Cal-Animage network initially started so that different schools could work together to exchange manga/fansubbed tapes, since they were somewhat difficult to find back then.

 The club's original name was "Cal-Animage Eta", which means we're the 7th Cal-Animage chapter. Cal-Animage Alpha is in UC Berkeley. Cal-Animage Eta was founded over 25 years ago, making JAC one the oldest clubs at UCLA!
# Photos for the slideshow.
# Each entry must contain the following:
# - description: Description text underneath the image.
# - path: Path to the image on the web server.
jacphotos:
 - description: JAC's 2018 Beach Episode
   path: /images/photos/photo1.jpg
 - description: JAC's 2018 Maid and Butler Cafe
   path: /images/photos/photo2.jpg
 - description: JAC's 2018 Winter Formal
   path: /images/photos/photo3.jpg
 - description: JAC's 2019 Winter Formal
   path: /images/photos/photo4.jpg
 - description: JAC at Anime Expo 2018
   path: /images/photos/photo5.jpg

# === JAC Meetings ===

# Day for weekend events.
weekendday: Saturdays
# Current quarter.
quarter: Spring
# Schedule of events for the quarter.
# Each entry in the list is a week and can have two entries, "meeting" and "weekend".
schedule:
 - meeting: OP/ED Night
 - meeting: Screenings Voting
   weekend: Little Tokyo Trip
 - meeting: Game Night
 - meeting: Special Screening
   weekend: Sawtelle Trip
 - meeting: Pictionary Night
 - meeting: Test of Courage Night
 - meeting: Karaoke Night
   weekend: Maid and Butler Cafe
 - meeting: Special Screening
   weekend: Beach Episode
 - meeting: Raffle
# Current quarterly screenings.
# Each entry must contain the following:
# - title: Anime title.
# - mal: MyAnimeList link.
# - image: Cover image to display.
screenings:
 - title: Fruits Basket (2019)
   mal: https://myanimelist.net/anime/38680/Fruits_Basket_2019
   image: https://cdn.myanimelist.net/images/anime/1447/99827.jpg
 - title: Kimetsu no Yaiba
   mal: https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba
   image: https://cdn.myanimelist.net/images/anime/1286/99889.jpg

# === Fresh Produce ===

# Fresh Produce meeting room.
freshroom: Ackerman Jamba Juice Lounge
# Fresh Produce meeting time.
freshtime: 8:00-10:00PM
# Fresh Produce meeting day.
freshday: Wednesdays
# Information about Fresh Produce.
# Written in Markdown.
freshabout: |
 Formerly an offshoot of the Japanese Animation Club, Fresh Productions (often known as "Fresh Produce") is a club for artists of all levels! We offer workshops, drawing lessons, special art supplies, and more. Whether you're a traditional or digital artist, come join us to hang out, draw together, and make friends in a chill environment!

 Check out our [Facebook](https://www.facebook.com/fpaucla/){:target="_blank"} page for more info! You can also find us on Discord!

# === Kirigami ===

# Information about Kirigami.
# Written in Markdown.
kirigamiabout: |
 # JAC's Idol Group

 Beginner-friendly dance and cosplay!

 Weekly Practice and Quarterly Performances

 Check us out on [Facebook](https://www.facebook.com/KiRiGaMiDancers/){:target="_blank"}!

# === Midnight Sessions ===

# Information about Midnight Sessions.
# Written in Markdown.
midnightabout: Love anime music? Interested in finding people to practice/arrange with? Stop by one of the weekly meetings of our one and only anime music club - [*The Midnight Sessions*](https://www.facebook.com/groups/344370402678778/){:target="_blank"}.

# === Join ===

# Mailing list sign-up form.
emailform: https://docs.google.com/forms/d/e/1FAIpQLSf1vl_musx4Pi1SQvjWUu-VOvxFniHWhJgVfJtWyGCJ4x1XIA/viewform
# Discord invite link.
discord: https://discordapp.com/invite/eXnRJaY
# Facebook group.
facebook: https://www.facebook.com/jacatucla

# === Misc ===

# JAC email address.
email: jacatucla@gmail.com

# === Jekyll Configuration ===

exclude: ['CNAME', 'README.md']

sass:
    style: compressed
