# === About JAC ===

# JAC meeting room.
jacroom: Franz 1260
# JAC meeting day.
jacday: Thursday
# JAC meeting time.
jactime: 7-9PM
# Information about JAC.
# Written in markdown.
# The line "%photos%" is replaced with the photo slideshow.
jacabout: |

 We're the Japanese Animation Club at UCLA! Welcome to our site! (ﾉ´ヮ´)ﾉ*:･ﾟ✧

 We’re a club dedicated to facilitating both on and off-campus gatherings for the appreciation of Japanese anime and culture! We welcome all anime fans to join us at our club-hosted events and local conventions, to meet with others who share the same passion for art and entertainment.

 %photos%

 We hold weekly club meetings. Please join us for screenings, awesome events, raffles, karaoke, cosplay, and much, much more!

 JAC is part of a larger network of collegiate anime clubs in California called "Cal Animage". The Cal-Animage network initially started so that different schools could work together to exchange manga/fansubbed tapes, since they were somewhat difficult to find back then.

 The club's original name was "Cal-Animage Eta", which means we're the 7th Cal-Animage chapter. Cal-Animage Alpha is in UC Berkeley. Cal-Animage Eta was founded over 25 years ago, making JAC one of the oldest clubs at UCLA!
# Photos for the slideshow.
# Each entry must contain the following:
# - description: Description text underneath the image.
# - path: Path to the image on the web server.
jacphotos:
 - description: Beach Episode 2018
   path: /images/photos/photo1.jpg
 - description: Maid and Butler Cafe 2019
   path: /images/photos/photo2.jpg
 - description: Winter Formal 2018
   path: /images/photos/photo3.jpg
 - description: Winter Formal 2019
   path: /images/photos/photo4.jpg
 - description: JAC at Anime Expo 2019
   path: /images/photos/photo5.jpg

# === JAC Meetings ===

# Day for weekend events. Comment out if none this quarter.
weekendday: Saturday
# Current quarter.
quarter: Winter
# Schedule of events for the quarter.
# Each entry in the list is a week and can have two entries, "meeting" and "weekend".
schedule:
 - meeting: Special Screening (Discord)
   weekend: Jackbox Night (Discord)
 - meeting: Winter Screenings + Voting (Discord)
   weekend: Sporcle Night (Discord)
 - meeting: Officer Q&A feat. Maids (Discord)
   weekend: Codenames Night (Discord)
 - meeting: Kahoot Night (Discord)
   weekend: Winter Social (Discord)
 - meeting: Pictionary Night
   weekend: Little Tokyo Trip
 - meeting: Valentine's Event
   weekend: Koreatown Trip
 - meeting: Karaoke Night
   weekend: Board Game Night
 - meeting: Anime Charades
   weekend: Dessert Night (Westwood)
 - meeting: Special Screening + Officer Elections + Raffle
# Current quarterly screenings.
# Each entry must contain the following:
# - title: Anime title.
# - mal: MyAnimeList link.
# - image: Cover image to display.
screenings:
- title: Sabikui Bisco
  mal: https://myanimelist.net/anime/48414
  image: https://cdn.myanimelist.net/images/anime/1446/118840l.jpg
- title: The Genius Prince's Guide to Raising a Nation Out of Debt
  mal: https://myanimelist.net/anime/47159
  image: https://cdn.myanimelist.net/images/anime/1263/119511l.jpg


# === Fresh Produce ===

# Fresh Produce meeting room.
#freshroom: Ackerman Jamba Juice Lounge
freshroom: Fresh Produce Discord
# Fresh Produce meeting day.
freshday: Wednesdays
# Fresh Produce meeting time.
freshtime: 8:00-10:00PM
# Information about Fresh Produce.
# Written in Markdown.
freshabout: |
 Formerly an offshoot of the Japanese Animation Club, Fresh Productions (often known as "Fresh Produce") is a club for artists of all levels! We offer workshops, drawing lessons, special art supplies, and more. Whether you're a traditional or digital artist, come join us to hang out, draw together, and make friends in a chill environment!

 Check out our [website](http://freshproductions.art/), [Facebook](https://www.facebook.com/fpaucla/){:target="_blank"}, and [Instagram](https://instagram.com/freshproductionsucla?igshid=1em21qn2e06w8){:target="_blank"} pages for more info! You can also join us on [Discord](https://discord.gg/DZpcjtg){:target="_blank"}!

# === Kirigami ===

# Information about Kirigami.
# Written in Markdown.
kirigamiabout: |
 # JAC's Idol Group

 Beginner-friendly dance and cosplay!

 Weekly Practice and Quarterly Performances

 Check us out on [Facebook](https://www.facebook.com/KiRiGaMiDancers/){:target="_blank"}!

# === Midnight Sessions ===

# Information about Midnight Sessions.
# Written in Markdown.
#midnightabout: Love anime music? Interested in finding people to practice/arrange with? Stop by one of the weekly meetings of our one and only anime music club - [*The Midnight Sessions*](https://www.facebook.com/groups/344370402678778/){:target="_blank"}.

# === Join ===

# Social media buttons.
# Each entry must contain the following:
# - icon: Button icon.
# - toptext: Text above the icon.
# - bottomtext: Text below the icon.
# - linkpath: URL path that the social link should be located at.
# - link: Actual social link to direct users to.
# Optional fields:
# - subtext: Smaller sub-text to show at the very bottom.
join:
 - icon: /images/social/discord.svg
   toptext: Can't wait to hang out?
   bottomtext: Join our Discord!
   subtext: (You must be logged in with your UCLA email to apply.)
   linkpath: /discord
   link: https://docs.google.com/forms/d/e/1FAIpQLSf3WCJ0h-bB778lLf-FKYtnomv61Lxp5fk6N3lxRjOfgHrP9w/viewform
 - icon: /images/social/facebook.svg
   toptext: Follow Us On
   bottomtext: For the latest updates on club events!
   linkpath: /facebook
   link: https://www.facebook.com/jacatucla
 - icon: /images/social/mail.png
   toptext: Join Our Mailing List
   bottomtext: For Weekly Announcements
   linkpath: /email
   link: https://docs.google.com/forms/d/e/1FAIpQLSf1vl_musx4Pi1SQvjWUu-VOvxFniHWhJgVfJtWyGCJ4x1XIA/viewform
 - icon: /images/social/instagram.svg
   toptext: Check out our
   bottomtext: For event photos and art!
   linkpath: /instagram
   link: https://www.instagram.com/jacatucla
 - icon: /images/social/twitter.svg
   toptext: Follow Us On
   bottomtext: For the latest updates on club events!
   linkpath: /twitter
   link: https://twitter.com/JACatUCLA
 - icon: /images/social/youtube.svg
   toptext: Check out our
   bottomtext: For events and other videos!
   linkpath: /youtube
   link: https://www.youtube.com/channel/UCtJyIawGRfmP9mgbWxXopSg

# === Misc ===

# JAC email address.
email: jacatucla@gmail.com

# === Jekyll Configuration ===

exclude: ['CNAME', 'README.md']

sass:
    style: compressed
